---
name: CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        experimental: [false]

    name: Python ${{ matrix.python-version}}
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip and install dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install nox
      - name: Test
        run: nox -s tests-${{ matrix.python-version }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results-${{ matrix.python-version }}
          path: test-results.xml

  test-typedoc-versions:
    runs-on: ubuntu-latest

    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        typedoc-version: ["0.25"]
        experimental: [false]

    name: Python ${{ matrix.python-version}} + typedoc ${{ matrix.typedoc-version }}
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip and install dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install nox
      - name: Test
        run: nox -s "test_typedoc-${{ matrix.python-version }}(typedoc='${{ matrix.typedoc-version }}')"

      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test_typedoc-results-${{ matrix.python-version }}-${{ matrix.typedoc-version }}
          path: test-results.xml
